### PR TITLE
Small tweak to prevent a NOTICE warning

### PR DESCRIPTION
**Pull request by greguly**
PHP Warning: Invalid argument supplied for foreach() ..... at line 81

### CODE REVIEW

**Comment by jamesgol** [comment]
I finally have some time to work on these issues and I'm curious if you can tell me how to reproduce this issue.  I just can't seem to find a case that this would happen.

**Comment by greguly** [comment]
I assume you are using `WP_DEBUG = true;` right?

**Comment by jamesgol** [comment]
Yes I have WP_DEBUG set to true.  $cart->cart_contents should always at least be an empty array which should not cause a warning to be printed.

**Comment by greguly** [comment]
Sorry, but I can't reproduce it right now. 
But it did happened at a client site. Let me try it at an old dev site of mine.

**Comment by greguly** [comment]
Next week shall try to reproduce and will post some screenshots along with steps.

Anyways, as of WC2.4,  WC()->cart is more than a simple array...

**Comment by jamesgol** [comment]
Yes, but $cart->cart_contents is a simple array.

I'd love to be able to fix this, but I prefer to understand when, when, why something is happening before implementing a fix.

**Comment by greguly** [comment]
Fair enough, let's leave as it is.

**Comment by jamesgol** [comment]
Closing this out for now, if it can be reproduced lets open it back up

**Pull request closed without merging**
