### PR TITLE
Add hook before delete expired item with proper parameters.

### PR DESCRIPTION
**Pull request by pablopaul**

### CODE REVIEW

**Comment by jamesgol** [comment]
Is there a reason you don't want to use the ''wc_csr_expired_cart_notice'' filter that gets called in this same block?

**Comment by pablopaul** [comment]
Because my basic understanding about filters vs actions is the following:
Filters are there to modify data.
Actions are there to add a action.

How is your understanding?

**Comment by jamesgol** [comment]
That is fundamentally correct, but in practice they are exactly the same except that a filter returns data where an action does not.  

So you can create a filter that just returns the default that is passed and also do the processing you need.

**Comment by pablopaul** [comment]
I got your point, but I still do not really would recommend that, read:

http://ottopress.com/2011/actions-and-filters-are-not-the-same-thing/

**Comment by jamesgol** [comment]
I'm all too familiar with issues like that, we often have to hook into places to make things work in situations the authors never intended (like what this plugin does). 

I'm not opposed to adding another filter/action I just like to restrict the number of added function calls when possible.

**Comment by jamesgol** [comment]
Merged.  Thanks!

**Pull request merged**
